# -*- coding: utf-8 -*-
"""NE School Map

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_8hgETqYo0oL1_jQOlTa1LLnbuAwj6w
"""

import folium
from folium.plugins import MarkerCluster

# School data: (latitude, longitude, region, official website, program page, student life, admissions)
schools = {
    "Tufts University": (
        42.4075, -71.1190, "Boston Area",
        "https://www.tufts.edu",
        "https://as.tufts.edu/sociology/",
        "https://students.tufts.edu/",
        "https://admissions.tufts.edu/"
    ),
    "Northeastern University": (
        42.3398, -71.0892, "Boston Area",
        "https://www.northeastern.edu",
        "https://damore-mckim.northeastern.edu/programs/marketing-undergraduate-concentration/",
        "https://studentlife.northeastern.edu/",
        "https://undergraduate.northeastern.edu/admissions/"
    ),
    "Boston University": (
        42.3505, -71.1054, "Boston Area",
        "https://www.bu.edu",
        "https://www.bu.edu/academics/questrom/courses/marketing/",
        "https://www.bu.edu/admissions/why-bu/student-life/",
        "https://www.bu.edu/admissions/"
    ),
    "Emerson College": (
        42.3520, -71.0656, "Boston Area",
        "https://www.emerson.edu",
        "https://emerson.edu/programs/marketing-communication-bs",
        "https://emerson.edu/emerson-life/campus",
        "https://emerson.edu/admission"
    ),
    "Brandeis University": (
        42.3650, -71.2607, "Boston Area",
        "https://www.brandeis.edu",
        "https://www.brandeis.edu/business/",
        "https://www.brandeis.edu/student-life/",
        "https://www.brandeis.edu/admissions/"
    ),
    "Babson College": (
        42.2987, -71.2654, "Boston Area",
        "https://www.babson.edu",
        "https://www.babson.edu/undergraduate/academics/concentrations/marketing/",
        "https://www.babson.edu/student-life/",
        "https://www.babson.edu/admission/undergraduate-school/"
    ),
    "Boston College": (
        42.3355, -71.1685, "Boston Area",
        "https://www.bc.edu",
        "https://www.bc.edu/bc-web/schools/carroll-school/academic-departments/marketing.html",
        "https://www.bc.edu/bc-web/campus-life.html",
        "https://www.bc.edu/bc-web/admission.html"
    ),
    "Vassar College": (
        41.6860, -73.8940, "NY/Upstate",
        "https://www.vassar.edu",
        "https://www.vassar.edu/sociology",
        "https://www.vassar.edu/campuslife",
        "https://www.vassar.edu/admissions"
    ),
    "Skidmore College": (
        43.0980, -73.7850, "NY/Upstate",
        "https://www.skidmore.edu",
        "https://www.skidmore.edu/sociology/",
        "https://www.skidmore.edu/campuslife/",
        "https://www.skidmore.edu/admissions/"
    ),
    "Ithaca College": (
        42.4228, -76.4948, "NY/Upstate",
        "https://www.ithaca.edu",
        "https://www.ithaca.edu/academics/school-business/marketing",
        "https://www.ithaca.edu/life-at-ic",
        "https://www.ithaca.edu/admission"
    ),
    "Hamilton College": (
        43.0506, -75.4066, "NY/Upstate",
        "https://www.hamilton.edu",
        "https://www.hamilton.edu/academics/departments/sociology",
        "https://www.hamilton.edu/campuslife",
        "https://www.hamilton.edu/admission"
    ),
    "Wheaton College (MA)": (
        41.9662, -71.1845, "MA/CT/Western NE",
        "https://wheatoncollege.edu",
        "https://wheatoncollege.edu/academics/programs/sociology/",
        "https://wheatoncollege.edu/campus-life/",
        "https://wheatoncollege.edu/admission/"
    ),
    "Wellesley College": (
        42.2936, -71.3067, "Boston Area",
        "https://www.wellesley.edu",
        "https://www.wellesley.edu/sociology",
        "https://www.wellesley.edu/life-at-wellesley",
        "https://www.wellesley.edu/admission"
    ),
    "Williams College": (
        42.7128, -73.2030, "MA/CT/Western NE",
        "https://www.williams.edu",
        "https://anso.williams.edu/",
        "https://www.williams.edu/student-life/",
        "https://www.williams.edu/admission-aid/"
    ),
    "Amherst College": (
        42.3732, -72.5199, "MA/CT/Western NE",
        "https://www.amherst.edu",
        "https://www.amherst.edu/academiclife/departments/anthropology_sociology",
        "https://www.amherst.edu/campuslife",
        "https://www.amherst.edu/admission"
    ),
    "College of the Holy Cross": (
        42.2383, -71.8089, "MA/CT/Western NE",
        "https://www.holycross.edu",
        "https://www.holycross.edu/academics/program/sociology",
        "https://www.holycross.edu/campus-life",
        "https://www.holycross.edu/apply"
    ),
    "Trinity College (CT)": (
        41.7458, -72.6927, "MA/CT/Western NE",
        "https://www.trincoll.edu",
        "https://www.trincoll.edu/sociology/",
        "https://www.trincoll.edu/studentlife/",
        "https://www.trincoll.edu/admissions/"
    ),
    "Connecticut College": (
        41.3782, -72.1031, "MA/CT/Western NE",
        "https://www.conncoll.edu",
        "https://www.conncoll.edu/academics/majors-departments-programs/departments/sociology/",
        "https://www.conncoll.edu/admission/faq/student-life/",
        "https://www.conncoll.edu/admission/"
    )
}

# Assign colors by region
region_colors = {
    "Boston Area": "red",
    "NY/Upstate": "blue",
    "MA/CT/Western NE": "green"
}

# Create map and cluster
m = folium.Map(location=[42.5, -72.0], zoom_start=7)
cluster = MarkerCluster().add_to(m)

# Add markers with multiple embedded HTML links
for name, (lat, lon, region, site, program, student_life, admission) in schools.items():
    html = f"""
    <h4>{name}</h4>
    <b>Region:</b> {region}<br><br>
    <a href='{site}' target='_blank'>🌐 Official Website</a><br>
    <a href='{program}' target='_blank'>📚 Program Page</a><br>
    <a href='{student_life}' target='_blank'>🎓 Student Life</a><br>
    <a href='{admission}' target='_blank'>📝 Admissions</a>
    """
    popup = folium.Popup(html, max_width=300)
    folium.Marker(
        location=[lat, lon],
        popup=popup,
        tooltip=name,
        icon=folium.Icon(color=region_colors[region], icon="info-sign")
    ).add_to(cluster)

m.save("college_map_with_links.html")
m